#impact parameter
min_b: 1
max_b: 50
grid_b: [0.1, 1, 10, 100, 500]

# angle of "impact" in cylindrical coordinates
min_psi: 0
max_psi: 360
grid_psi: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 280, 285, 290, 295, 300, 305, 310, 315, 320, 325, 330, 335, 340, 345, 350, 355]

# velocity in z direction in cylindrical coordinates of the stream
min_vz: 50
max_vz: 350
grid_vz: 10

# velocity in angle direction in cylindrical coordinates of the stream
min_vpsi: 5
max_vpsi: 100
grid_vpsi: 5

# time of interaction
min_t: 350
max_t: 550
grid_t: 5

# log of the mass of the perturber
min_logm: 6
max_logm: 7.0
grid_logm: [6.4, 6.5, 6.6, 6.7, 6.8, 6.9]

# core radius of the perturber, perhaps not used
min_core: 0.1
max_core: 100
grid_core: [0.1]
